# Generated by Django 3.2.9 on 2021-11-26 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carac_moviles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('tamaño', models.CharField(max_length=50)),
                ('capacidad', models.CharField(max_length=50)),
                ('mpx_camara', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='moviles')),
                ('precio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Protector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='moviles')),
                ('precio', models.CharField(max_length=50)),
                ('movil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vistas.carac_moviles')),
            ],
        ),
        migrations.CreateModel(
            name='Fundas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='moviles')),
                ('precio', models.CharField(max_length=50)),
                ('movil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vistas.carac_moviles')),
            ],
        ),
    ]
