# Generated by Django 3.2.9 on 2021-11-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviles',
            options={'verbose_name': 'moviles'},
        ),
        migrations.AlterField(
            model_name='moviles',
            name='caracteristicas',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='moviles',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
