# Generated by Django 3.2.9 on 2021-11-22 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviles', '0003_auto_20211119_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carac_moviles',
            options={},
        ),
    ]
